[project]
name = "site-watcher"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
  "httpx>=0.27.0",
  "beautifulsoup4>=4.12.3",
  "lxml>=5.2.2",
  "python-dotenv>=1.0.1",
  "playwright>=1.45.0",
]

[tool.uv]
